// Generated by CoffeeScript 1.3.3

/*
// ==UserScript==
// @author         kneo
// @version        0.0.1
// @name           kneosmth
// @namespace      https://github.com/iambus
// @description    It's my style
// @include        http://www.newsmth.net/bbspst.php?*
// ==/UserScript==
*/


(function() {
  var ajax, encode_form, gm_ajax, insert_post_button, is_posting, overwrite_hotkey, post, redirect_ok;

  is_posting = function() {
    return /^http:\/\/(www\.)newsmth\.net\/bbspst\.php\?/.test(window.location);
  };

  encode_form = function(form) {
    var k, v;
    return ((function() {
      var _results;
      _results = [];
      for (k in form) {
        v = form[k];
        _results.push(encodeURIComponent(k) + '=' + encodeURIComponent(v));
      }
      return _results;
    })()).join('&');
  };

  ajax = function(url, form, callback) {
    var xhr;
    xhr = new XMLHttpRequest;
    xhr.onreadystatechange = function() {
      return callback(xhr);
    };
    xhr.open("Post", url, true);
    xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
    xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
    return xhr.send(encode_form(form));
  };

  gm_ajax = function(url, form, callback) {
    return GM_xmlhttpRequest({
      method: 'POST',
      url: url,
      data: encode_form(form),
      headers: {
        "Content-type": "application/x-www-form-urlencoded",
        "X-Requested-With": "XMLHttpRequest"
      },
      onload: callback
    });
  };

  redirect_ok = function(board, board_cn, id, is_reply) {
    var op;
    op = is_reply ? '回复文章' : '发表文章';
    document.getElementsByTagName('BODY')[0].innerHTML = "<div class=\"nav smaller\"><a href=\"mainpage.html\">水木社区</a><span id=\"idExp\"></span> → <a href=\"bbsdoc.php?board=" + board + "\">" + board_cn + "</a> → " + op + "</div>\n操作成功: 发文成功！<br/>本页面将在3秒后自动返回版面文章列表<div class=\"medium\"><ul><b>您可以选择以下操作：</b>\n<li><a href='mainpage.html'>返回首页</a></li><li><a href='bbsdoc.php?board=" + board + "'>返回 " + board_cn + "</a></li></ul>\n<br /><br />";
    return setTimeout((function() {
      return window.location.href = "bbsdoc.php?board=" + board;
    }), 3000);
  };

  post = function() {
    var board, reid, signature, text, title, _ref, _ref1;
    board = window.location.toString().match(/board=([\w.]+)/)[1];
    reid = (_ref = (_ref1 = window.location.toString().match(/reid=(\d+)/)) != null ? _ref1[1] : void 0) != null ? _ref : '0';
    title = document.getElementsByName('title')[0].value;
    text = document.getElementsByName('text')[0].value;
    signature = document.getElementsByName('signature')[0].value;
    gm_ajax("/nForum/article/" + board + "/ajax_post.json", {
      id: reid,
      subject: title,
      content: text,
      signature: signature
    }, function(xhr) {
      var board_cn, id, result;
      if (xhr.readyState !== 4) {
        return;
      }
      if (xhr.status !== 200) {
        alert('error: ' + xhr.status);
        return;
      }
      result = JSON.parse(xhr.responseText);
      if (result.ajax_st === 1) {
        board_cn = result.list[0].text.substring(3);
        board = result.list[0].url.replace(/.*\//, '');
        id = result.list[1].url.replace(/.*\//, '');
        return redirect_ok(board, board_cn, id, reid !== '0');
      } else {
        return alert(xhr.responseText);
      }
    });
  };

  overwrite_hotkey = function() {
    var textarea;
    textarea = document.getElementsByName('text')[0];
    textarea.onkeydown = null;
    return textarea.addEventListener('keydown', function(event) {
      var key, _ref;
      key = (_ref = event.keyCode) != null ? _ref : event.charCode;
      if ((key === 87 && event.ctrlKey) || (key === 13 && event.ctrlKey)) {
        event.preventDefault();
        event.stopPropagation();
        post();
        return false;
      }
      return true;
    });
  };

  insert_post_button = function() {
    var button, check, check_label, old_button, opers, post_oper, verify_oper;
    opers = document.getElementsByClassName('oper');
    if (opers.length !== 2) {
      return;
    }
    verify_oper = opers[0], post_oper = opers[1];
    verify_oper.hidden = true;
    old_button = post_oper.children[0];
    old_button.value = '发表';
    old_button.title = '使用原来的方式发表文章（请手动输入验证码）';
    button = document.createElement('input');
    button.type = 'button';
    button.value = '直接发表';
    button.title = '不必输入验证码';
    post_oper.insertBefore(button, old_button);
    button.addEventListener('click', post);
    check = document.createElement('input');
    check.type = 'checkbox';
    post_oper.insertBefore(check, old_button);
    check.addEventListener('click', function(event) {
      verify_oper.hidden = !event.target.checked;
    });
    check_label = document.createTextNode('显示验证码');
    return post_oper.insertBefore(check_label, old_button);
  };

  if (is_posting()) {
    insert_post_button();
    overwrite_hotkey();
  }

}).call(this);
